### ISSUE TITLE
Make it explicit that you begin with an example.

### ISSUE THREAD

**Issue by ivan-zapreev-work** [IHE/HIE-Whitepaper#111]
**Section Number**
Section 5.4

**Issue**

Consider the next sentence:

>In this way the PCP office can discover the ...

What does a PCP office have to do with PMIR, or is this just an example?

**Proposed Change** 

Make it clear that this is the beginning of an example.

**Priority**:
Medium

**Comment by JohnMoehrke** [comment]
the whole section is an example. I think it is clear this is the example.

**Comment by JohnMoehrke** [comment]
update section 5.4 as shown 

For example a PCP's consumer system may query the PMIR registry to receive the shared master Patient Identity (aka. golden identity) based on their local identifiers or based on the identifying characteristics of the patient. In this way the PCP can discover the master Patient Identity so that it can communicate with the systems in that community using a known patient identifier. This query uses Patient Identity Cross-referencing for Mobile (PIXm) or Patient Demographics Query for Mobile (PDQm).

**Comment by ivan-zapreev-work** [comment]
Looks like a very good change to me
