### ISSUE TITLE
Decision graphic include mXDE

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#123]
for those that have a need for easier consumption

**Comment by JohnMoehrke** [comment]
Figure 3.4-1 should explain that mXDE consumption is reliant on MHD, thus if you want QEDm/mXDE then you need MHD, and thus the decision graph is important for the consumption side.

**Comment by CharlesParisot** [comment]
John,

 

I am puzzled by this comment:

It gives the incorrect impression that you may not operate mXDE along with XDS and requires MHD.

MHD and XDS are alternative choices to access the documents.

 

Probably, the comment is lacking some context.  Is it ?

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : mercredi 10 février 2021 12:45
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] Decision graphic include mXDE (#123)

 

Figure 3.4-1 should explain that mXDE consumption is reliant on MHD, thus if you want QEDm/mXDE then you need MHD, and thus the decision graph is important for the consumption side.

**Comment by JohnMoehrke** [comment]
I thought that the Provenance linkage did not provide a non MHD way (i.e. detail for XDS or XCA)..  I just looked again, and it does include both. (the what.reference for MHD, and the what.indntifier for XDS/XCA). One might not have enough information for XCA depending on how critical HCID is relative to finding the repository.

So, agree this should NOT be added to the whitepaper.

**Comment by CharlesParisot** [comment]
John,

 

Thanks.  

XCA is explicitly out of scope, but implicitly included as we have everything we need for XCA access through XDS Doc Consumer.

The HCID is cached out of the XDS Query (mapped to an XCA Query) and returned in the XDS Query response to be used ofr the XDS Retrieve, and then conveyed through the XCA Cross-Community Retrieve.

 

The same mechanism works perfectly for the direct use of the XCA Cross Community Initiating Gateway Actor, but we did not include it in mXDE because this would have created a third option, making the profile look more complex, because you have to federate the relayed QEDm queries through the Cross Community Initiating Gateway Actor, which could be described but would have made the profile appear too complex. 

 

Anyway, if you want the white paper to be complete you can state that XCA Federated XDS Domain, each supporting mXDE, is deployable.

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : mercredi 10 février 2021 16:13
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Charles Parisot <charles@interopehealth.com>; Comment <comment@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] Decision graphic include mXDE (#123)

 

I thought that the Provenance linkage did not provide a non MHD way (i.e. detail for XDS or XCA).. I just looked again, and it does include both. (the what.reference for MHD, and the what.indntifier for XDS/XCA). One might not have enough information for XCA depending on how critical HCID is relative to finding the repository.

So, agree this should NOT be added to the whitepaper.

**Comment by JohnMoehrke** [comment]
I think the whitepaper should not go into that detail. I recommend we just close this.

**Comment by CharlesParisot** [comment]
John,

 

As long as you mention that there is a choice between XDS and MHD to retrieve the document from the provenance information, I am fine to simplify.

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : mercredi 10 février 2021 18:37
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Charles Parisot <charles@interopehealth.com>; Comment <comment@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] Decision graphic include mXDE (#123)

 

I think the whitepaper should not go into that detail. I recommend we just close this.
