### ISSUE TITLE
Unclear sentences in 2.3.1 FHIR-Document vs CDA-Document

### ISSUE THREAD

**Issue by oliveregger** [IHE/HIE-Whitepaper#124]
2.3.1 FHIR-Document vs CDA-Document

**Issue**
. This model enables more easy on the Content Consumer.

**Proposed Change** 
 I don't know what the author intended to be said.

**Issue**
There is clear identity (.id) of each of these resources to so they are clearly distinct

**Proposed Change** 
There is a distinct identity of each resource.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by CharlesParisot** [comment]
This discussion should be removed from the HIE white paper.

It is content specific and not in the purview of IHE ITI, but of PCC.

 

Charles

 

De : Oliver Egger <notifications@github.com> 
Envoyé : jeudi 21 janvier 2021 10:51
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [IHE/HIE-Whitepaper] Unclear sentences in 2.3.1 FHIR-Document vs CDA-Document (#124)

 

2.3.1 FHIR-Document vs CDA-Document

Issue
. This model enables more easy on the Content Consumer.

Proposed Change
I don't know what the author intended to be said.

Issue
There is clear identity (.id) of each of these resources to so they are clearly distinct

Proposed Change
There is a distinct identity of each resource.

Priority:

*	Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
I agree with Oliver, the sentence needs to be likely removed. It is an unnecessary argumentantative statement. The section goal was to point out that Document Sharing is content agnostic, and to point out that because of this principle it already supports FHIR in addition to CDA. 

I disagree with Charles that the section should be removed. It is very important for the success of Document Sharing that it is clear this is NOT a competition with FHIR.

**Comment by CharlesParisot** [comment]
My comment came from the fact that FHIR documents are still largely a concept without legs, so bragging about that on behalf of FHIR is not helping anyone.  Release 5 may hopefully fix these gaps.

 

The content neutrality has nothing to do with FHIR documents and has been demonstrated with CDA, DICOM, BPMN, and other content we do not want to promote HL7V2 persisted messages, naked PDF and JPG, etc.

 

Charles

 

De : John Moehrke <notifications@github.com> 
Envoyé : mercredi 10 février 2021 11:02
À : IHE/HIE-Whitepaper <HIE-Whitepaper@noreply.github.com>
Cc : Charles Parisot <charles@interopehealth.com>; Comment <comment@noreply.github.com>
Objet : Re: [IHE/HIE-Whitepaper] Unclear sentences in 2.3.1 FHIR-Document vs CDA-Document (#124)

 

I agree with Oliver, the sentence needs to be likely removed. It is an unnecessary argumentantative statement. The section goal was to point out that Document Sharing is content agnostic, and to point out that because of this principle it already supports FHIR in addition to CDA.

I disagree with Charles that the section should be removed. It is very important for the success of Document Sharing that it is clear this is NOT a competition with FHIR.
