### ISSUE TITLE
consider XCPD variations 

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#16]
Should XCPD variations be discussed? record location, cross-reference, demographics, etc.

Ask of @jlamy to review and offer insights on XCPD variations that should be highlighted. This is not a technical text, recommended text should be appropriate and lead the reader to the Profile for further detail and technical specifications

**Comment by JohnMoehrke** [comment]
discussed this with @jlamy . This should be just a few sentences. Not a technical overview, leave that to the profile text. Main message is to point out to executive level audience that XCPD has some different variations to support different deployment and policy domains.

**Comment by JohnMoehrke** [comment]
@jlamy any progress on XCPD variations in HIE whitepaper speak?

**Comment by JohnMoehrke** [comment]
might this be handled in the new table that charles added around patient identity management? I don't know, because I don't understand the modes...

**Comment by JohnMoehrke** [comment]
I propose that the existing text covers this well enough @jlamy do you agree?

**Comment by jlamy** [comment]
I think it's almost there. What's missing is a bit more focus on record location, which is what differentiates XCPD from PDQ and PIX. PDQ and PIX deal with logical patient identifiers - even if a patient has multiple ids from different logical domains, in a single community they represent one location. In a federated community environment, each community is a distinct potential location for patient info, even if two communities happen to use the same patient id from a shared patient domain. I'll see where the text can be tweaked.

**Comment by jlamy** [comment]
Let's modify the second paragraph as follows:

XCPD is similar in function to PDQ but is used with the Federated Discovery and Retrieve model of Document Sharing. XCPD enables discovery that a patient is known and potentially has information at a given community. Once this is known, the Initiating Gateway can use XCA to obtain documents for that patient from that community. XCPD also enables centralized "Record Locator Services" that allow Initiating Gateways to discover a patient is known in multiple communities without having to ask each one. XCPD supports a hierarchical approach which bridges communities that might use PIX or PDQ internally.

**Comment by jlamy** [comment]
Ok, edits ready to go with a pull request. But I have a question:

On the call we decided to strike the part that said PDQm could be used similarly to XCPD, because PDQm doesn't have the concept of community. I still think we should strike it, but my reasoning is more nuanced:
- PDQm could be used by a community to confirm whether that community alone knows the patient, so it would cover the basic XCPD flow, just not the RLS/PLQ/HDL flow.
- However, I would think that a real FHIR replacement for XCPD wouldn't use the simple HTTP search function, but rather the Patient-match operation, which reflects probabilistic matching.
