### ISSUE TITLE
Reference a Case-Study from OpenHIE

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/HIE-Whitepaper#17]

**Comment by djritz** [comment]
Are we looking for a country case study example (which are not simple/trivial to do... b/c we typically need MOH permission)? It may be easier -- rather than a case study -- to prepare an example of how the OpenHIE architecture "works" and the ways it aligns with, for example, MHDS. Would that approach be OK?

**Comment by JohnMoehrke** [comment]
Mostly highlevel description of OpenHIE and possibly links to some external descriptions.

**Comment by JohnMoehrke** [comment]
@djritz have you made progress on getting an OpenHIE case-study published so that we can reference it?

**Comment by djritz** [comment]
beyond bringing it up on the most recent (semi-monthly) OpenHIE architecture call, no. i haven't authored anything and won't have time to do that until late august (i'm buried in multiple very-active projects). it may be worthwhile to survey some existing content and see if any of it is on point. @lduncan-intrah -- do you know of any papers (e.g. Instant OpenHIE) that may be applicable?

**Comment by JohnMoehrke** [comment]
https://digitalprinciples.org/wp-content/uploads/PDD_CaseStudy-OpenHIE_v3.pdf

**Comment by JohnMoehrke** [comment]
@djritz besides pointing at the published CaseStudy on OpenHIE... I think we were wondering if you could write a paragraph that would bridge our paper to that case study.

**Comment by JohnMoehrke** [comment]
@djritz please confirm if you are going to write a paragraph introduction to the OpenHIE paper?

**Comment by djritz** [comment]
@JohnMoehrke -- yes... I will write a paragraph that "introduces" the paper. In truth... a lot has happened since this paper was published, so one of the jobs of that "bridge" will be to point to those differences and to where the most up-to-date info can be found. Too busy to get to that for the next couple of weeks, tho. Sorry... day-job stuff is very heavy lately...

**Comment by JohnMoehrke** [comment]
Excellent. Goal is to get this done by end of October, so that it is ready for our November meeting.

**Comment by djritz** [comment]
@JohnMoehrke -- here is a draft introductory paragraph:

In 2012, an initiative was launched, with donor support from the US President's Emergency Plan for AIDS Relief (**PEPFAR**; https://www.state.gov/pepfar/), to develop an open source health enterprise architecture that could be adapted and adopted by low and middle income countries (**LMIC**) to support national-scale health data sharing. The Open Health Information Exchange (**OpenHIE**; https://ohie.org/) framework describes a comprehensive family of digital health workflows expressed in terms of IHE Profiles. A case study of OpenHIE, and version 1 of its architecture, was published by the **Principles for Digital Development**: https://digitalprinciples.org/wp-content/uploads/PDD_CaseStudy-OpenHIE_v3.pdf.  The latest version (v2) of the OpenHIE architecture, which is based on the **HL7 FHIR** specification (as profiled by IHE's Mobile Health Document Sharing (**MHDS**) specification), can be found here: https://ohie.org/architecture-specification/.

**Comment by JohnMoehrke** [comment]
I will put this in place of the text already describing OpenHIE.
